export const SAVED_STUDENT = 'SAVED_STUDENT';
export const RECEIVED_STUDENTS = 'RECEIVED_STUDENTS';
export const DELETED_STUDENT = 'DELETED_STUDENT';

export const STUDENT_LIST_EDITABLE = 'STUDENT_LIST_EDITABLE';
export const STUDENT_LIST_NOT_EDITABLE = 'STUDENT_LIST_NOT_EDITABLE';